export const theme = {
  colors: {
    background: '#F8F9FB',
    surface: '#FFFFFF',
    textPrimary: '#111827',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    accent: '#2563EB',
    accentSoft: '#EFF6FF',
    accentRing: '#DBEAFE',
    border: '#E5E7EB',
    savings: '#059669',
    savingsSoft: '#ECFDF5',
    savingsBorder: '#A7F3D0',
    delete: '#EF4444',
    deleteSoft: '#FEF2F2',
    keep: '#10B981',
    keepSoft: '#ECFDF5',
    categoryPurple: '#7C3AED',
    categoryPurpleSoft: '#F5F3FF',
    categoryOrange: '#EA580C',
    categoryOrangeSoft: '#FFF7ED',
    categoryPink: '#DB2777',
    categoryPinkSoft: '#FDF2F8',
    categoryYellow: '#CA8A04',
    categoryYellowSoft: '#FEFCE8',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 20,
    pill: 999,
  },
  typography: {
    hero: 40,
    title: 28,
    subtitle: 18,
    body: 16,
    caption: 13,
    label: 12,
  },
} as const;

export type Theme = typeof theme;
